$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$outputDirectory = Join-Path $root "dist"
$outputPath = Join-Path $outputDirectory "modules.luau"

function Get-RelativePath([string] $path) {
	return $path.Substring($root.Length).TrimStart('\', '/').Replace('\', '/')
}

function Get-LongString([string] $source) {
	$equals = ""
	while ($source.Contains("]" + $equals + "]")) {
		$equals += "="
	}
	return "[" + $equals + "[" + $source + "]" + $equals + "]"
}

$files = Get-ChildItem -LiteralPath $root -Recurse -File -Filter "*.luau" |
	Where-Object {
		$relative = Get-RelativePath $_.FullName
		$relative -notmatch "(^|/)tests/" -and
		$relative -notmatch "^dist/" -and
		$relative -notmatch "^tools/" -and
		$relative -ne "logic.luau" -and
		$relative -ne "loader.luau"
	} |
	Sort-Object { Get-RelativePath $_.FullName }

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("-- Generated by tools/build-module-bundle.ps1. Do not edit directly.")
$lines.Add("return {")
foreach ($file in $files) {
	$relative = Get-RelativePath $file.FullName
	$source = [System.IO.File]::ReadAllText($file.FullName)
	$lines.Add("`t[`"$relative`"] = " + (Get-LongString $source) + ",")
}
$lines.Add("}")

[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outputPath, ($lines -join "`n") + "`n", $encoding)

Write-Output ("Bundled {0} modules into {1}" -f $files.Count, $outputPath)
